name: bp_monitor_iot
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  mqtt_client: ^10.4.1
  firebase_core: ^4.4.0
  cloud_firestore: ^6.1.2
  fl_chart: ^1.1.1
  equatable: ^2.0.5
  intl: ^0.20.2
  typed_data: ^1.4.0
  connectivity_plus: ^7.0.0
  url_launcher: ^6.3.1
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: 0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/team_image/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/CSBPM_icon.jpeg"
  min_sdk_android: 21
  adaptive_icon_background: "#00C853"
  adaptive_icon_foreground: "assets/icons/CSBPM_icon.jpeg"
