// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATu0Y6kfgdKQZ51sBK7KsnqOe7u1v8PoI',
    appId: '1:504816582582:web:319b19f9dc9f5ae0424b17',
    messagingSenderId: '504816582582',
    projectId: 'bp-project-53add',
    authDomain: 'bp-project-53add.firebaseapp.com',
    databaseURL: 'https://bp-project-53add-default-rtdb.firebaseio.com',
    storageBucket: 'bp-project-53add.firebasestorage.app',
    measurementId: 'G-6NPQL2FQNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4IUXArh8tQ5MRPvwT7o53Cny7bOUfsTQ',
    appId: '1:504816582582:android:480922988f2a402f424b17',
    messagingSenderId: '504816582582',
    projectId: 'bp-project-53add',
    databaseURL: 'https://bp-project-53add-default-rtdb.firebaseio.com',
    storageBucket: 'bp-project-53add.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCb5S3xwps3KgpLA2Cb5GuTG0Z1acItYE',
    appId: '1:504816582582:ios:766edb1a6def87cc424b17',
    messagingSenderId: '504816582582',
    projectId: 'bp-project-53add',
    databaseURL: 'https://bp-project-53add-default-rtdb.firebaseio.com',
    storageBucket: 'bp-project-53add.firebasestorage.app',
    iosBundleId: 'com.example.bpMonitorIot',
  );
}
